### ISSUE TITLE
IOS Reader applications 'utf8' error during communication with Ipad

### ISSUE THREAD

**Issue by Orblux** [Philantrop/calibre-ios-reader-applications#100]
Hello,
I've an issue with the communication between Calibre and the Marvin application on an IPad.
When the Marvin's icon appears on the Calibre's toolbar, and the listenning task begins (as usual), Calibre finishes to print an error message : 

'utf8' codec can't decode byte 0xe9 in position 58: invalid continuation byte
Traceback (most recent call last):
File "site-packages\calibre\gui2\device.py", line 86, in run
File "site-packages\calibre\gui2\device.py", line 490, in _books
File "C:\Users\Isis\AppData\Local\Temp\calibre_guzzjx\ezlryu_ios_local_db\Marvin_overlays.py", line 435, in books
File "calibre_plugins.ios_reader_apps.__init__", line 1392, in _log_metrics
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 58: invalid continuation byte

- Calibre 1.48 (french)
- IOS Reader Application 1.4.1
- Windows 8, 64bits
- IPad IOS 7.1.2
- Itunes 11.3.0.54

Here it is the debug_log.txt : 

calibre 1.48  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.5
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
DEBUG:    0.0 iOSReaderApp:initialize(v1.4.1) 
DEBUG:    0.0 iOSReaderApp:compile_ui() 
DEBUG:    0.2 iOSReaderApp:_init_prefs(prefs created under v1.4.1) 
DEBUG:    0.2  debug_libimobiledevice: False
DEBUG:    0.2  debug_plugin: True
DEBUG:    0.2  development_mode: False
DEBUG:    0.2  device_booklist_cache_limit: 10
DEBUG:    0.2  device_booklist_caching: False
DEBUG:    0.2  kindle_enabled_formats: [u'MOBI', u'PDF']
DEBUG:    0.2  kindle_supported_formats: [u'MOBI', u'PDF']
DEBUG:    0.2  marvin_edit_collections_cb: False
DEBUG:    0.2  marvin_protect_rb: True
DEBUG:    0.2  marvin_replace_rb: False
DEBUG:    0.2  marvin_update_rb: False
DEBUG:    0.2  plugin_diagnostics: True
DEBUG:    0.2  preferred_reader_app: u'Marvin'
DEBUG:    0.2 iOSReaderApp:_get_connected_device_info() 
DEBUG:    4.6  mounting 'com.appstafarian.MarvinIP'
DEBUG:    5.8 libiMobileDevice:mount_ios_app(com.appstafarian.MarvinIP: ApplicationLookupFailed) 
DEBUG:    5.8  mounting 'com.appstafarian.MarvinIP-free'
DEBUG:    7.0 iOSReaderApp:_class_reconfigure('Marvin') 
DEBUG:    7.0 iOSReaderApp:_load_reader_app_overlays('Marvin') 
DEBUG:    7.0  loading 58 overlays
DEBUG:    7.0  adding overlay '_compare_mainDb_profiles()'
DEBUG:    7.0  adding overlay '_cover_subpath()'
DEBUG:    7.0  adding overlay '_cover_to_thumb()'
DEBUG:    7.0  adding overlay '_create_cover_element()'
DEBUG:    7.0  adding overlay '_create_empty_booklist_db()'
DEBUG:    7.0  adding overlay '_create_new_book()'
DEBUG:    7.0  adding overlay '_dehydrate_booklist()'
DEBUG:    7.0  adding overlay '_establish_local_booklist_db_path()'
DEBUG:    7.0  adding overlay '_evaluate_original_cover()'
DEBUG:    7.0  adding overlay '_evaluate_replaceable_cover()'
DEBUG:    7.0  adding overlay '_get_field_items()'
DEBUG:    7.0  adding overlay '_get_opf_tree()'
DEBUG:    7.0  adding overlay '_get_opf_xml()'
DEBUG:    7.0  adding overlay '_initialize_overlay()'
DEBUG:    7.1  adding overlay '_localize_booklist_db()'
DEBUG:    7.1  adding overlay '_localize_database_path()'
DEBUG:    7.1  adding overlay '_parse_version()'
DEBUG:    7.1  adding overlay '_parse_xml()'
DEBUG:    7.1  adding overlay '_profile_db()'
DEBUG:    7.1  adding overlay '_rehydrate_booklist()'
DEBUG:    7.1  adding overlay '_remove_existing_copy()'
DEBUG:    7.1  adding overlay '_report_upload_results()'
DEBUG:    7.1  adding overlay '_reset_ios_connection()'
DEBUG:    7.1  adding overlay '_restore_from_snapshot()'
DEBUG:    7.1  adding overlay '_schedule_metadata_update()'
DEBUG:    7.1  adding overlay '_snapshot_booklist()'
DEBUG:    7.1  adding overlay '_stage_command_file()'
DEBUG:    7.1  adding overlay '_update_epub_metadata()'
DEBUG:    7.1  adding overlay '_validate_dehydrated_booklist()'
DEBUG:    7.1  adding overlay '_wait_for_command_completion()'
DEBUG:    7.1  adding overlay '_watchdog_timed_out()'
DEBUG:    7.1  adding overlay '_xform_metadata_via_plugboard()'
DEBUG:    7.1  adding overlay 'add_books_to_metadata()'
DEBUG:    7.1  adding overlay 'books()'
DEBUG:    7.1  adding overlay 'can_handle()'
DEBUG:    7.1  adding overlay 'can_handle_windows()'
DEBUG:    7.1  adding overlay 'delete_books()'
DEBUG:    7.1  adding overlay 'eject()'
DEBUG:    7.1  adding overlay 'from_json()'
DEBUG:    7.1  adding overlay 'get_busy_flag()'
DEBUG:    7.1  adding overlay 'get_cc_mapping()'
DEBUG:    7.1  adding overlay 'get_file()'
DEBUG:    7.1  adding overlay 'guess_type()'
DEBUG:    7.1  adding overlay 'is_usb_connected()'
DEBUG:    7.1  adding overlay 'is_usb_connected_windows()'
DEBUG:    7.1  adding overlay 'post_yank_cleanup()'
DEBUG:    7.1  adding overlay 'prepare_addable_books()'
DEBUG:    7.1  adding overlay 'remove_books_from_metadata()'
DEBUG:    7.1  adding overlay 'set_busy_flag()'
DEBUG:    7.1  adding overlay 'set_cc_mapping()'
DEBUG:    7.1  adding overlay 'shutdown()'
DEBUG:    7.1  adding overlay 'sort_key()'
DEBUG:    7.1  adding overlay 'startup()'
DEBUG:    7.1  adding overlay 'sync_booklists()'
DEBUG:    7.1  adding overlay 'thumbnail()'
DEBUG:    7.1  adding overlay 'to_json()'
DEBUG:    7.1  adding overlay 'upload_books()'
DEBUG:    7.1  adding overlay 'xml_to_unicode()'
DEBUG:    7.1 iOSReaderApp:_initialize_overlay(Marvin) 
DEBUG:    7.1  existing thumb cache at 'C:\Users\Isis\AppData\Local\calibre-cache\Marvin\thumbs.zip'
DEBUG:    7.1  ~~~~~~~~~~~~~~~~~~~~~~~~~ switching to Marvin overlay ~~~~~~~~~~~~~~~~~~~~~~~~~~
ITUNES.__init__():
 Debug logging enabled
Starting up...
DEBUG:    8.1 iOSReaderApp:startup() 
DEBUG:    8.1 iOSReaderApp:_dump_installed_plugins() 
DEBUG:    8.1  plugin           author       version
DEBUG:    8.1  ---------------  -----------  -----
DEBUG:    8.1  Find Duplicates  Grant Drake  1.6.2 
DEBUG:    8.1  ---------------  -----------  -----
DEBUG:    8.1  Waiting for calibre connector...
Ignoring invalid sort_columns_at_startup tweak, with error:
Started up in 1.75 seconds with 2535 books
DEBUG:   18.4  Marvin version: (2, 7, 2)
DEBUG:   19.5 iOSReaderApp:reset() 
DEBUG:   19.5 iOSReaderApp:open() 
DEBUG:   19.5   Vendor ID (vid):05ac Product ID: (pid):12ab
DEBUG:   19.5 iOSReaderApp:set_progress_reporter() 
Job: 1 Lit les informations de l’appareil started
DEBUG:   19.5 iOSReaderApp:get_device_information() 
DEBUG:   19.5   DeviceClass          : iPad
DEBUG:   19.5   DeviceColor          : black
DEBUG:   19.5   DeviceName           : iPad de Kévin
DEBUG:   19.5   FSBlockSize          : 4096
DEBUG:   19.5   FSFreeBytes          : 8,805,179,392
DEBUG:   19.5   FSTotalBytes         : 14,175,248,384
DEBUG:   19.5   FirmwareVersion      : iBoot-1940.10.58
DEBUG:   19.5   HardwareModel        : P101AP
DEBUG:   19.5   ModelNumber          : MD510
DEBUG:   19.5   PasswordProtected    : False
DEBUG:   19.5   ProductType          : iPad3,4
DEBUG:   19.5   ProductVersion       : 7.1.2
DEBUG:   19.5   SerialNumber         : DLXKFAF8F182
DEBUG:   19.5   TimeIntervalSince1970: 1407832617.0
DEBUG:   19.5   TimeZone             : Europe/Paris
DEBUG:   19.5   TimeZoneOffsetFromUTC: 7200.0
DEBUG:   19.5   UniqueDeviceID       : f99a09f75c5205ed8167b6dc43e70d17695361f8
DEBUG:   19.5 iOSReaderApp:free_space() 
DeviceJob: 1 Lit les informations de l’appareil done, calling callback
DeviceJob: 1 Lit les informations de l’appareil callback returned
DEBUG:   19.6 iOSReaderApp:set_progress_reporter() 
Job: 2 Lire la liste des livres à partir de l’appareil connecté started
DEBUG:   19.6 iOSReaderApp:books() 
DEBUG:   19.6 iOSReaderApp:_localize_database_path() 
DEBUG:   19.6  copying local_db from u'/Library/mainDb.sqlite'
DEBUG:   19.7 iOSReaderApp:_restore_from_snapshot() 
DEBUG:   19.7  Analyzing local booklist
DEBUG:   19.7  local booklist.db validated
DEBUG:   19.7 iOSReaderApp:_rehydrate_booklist() 
DEBUG:   19.7 iOSReaderApp:_log_metrics(Marvin) 
Job: 1 Lit les informations de l’appareil finished
Pas de détail disponible.
DeviceJob: 2 Lire la liste des livres à partir de l’appareil connecté done, calling callback
DeviceJob: 2 Lire la liste des livres à partir de l’appareil connecté callback returned
Job: 2 Lire la liste des livres à partir de l’appareil connecté finished
'utf8' codec can't decode byte 0xe9 in position 58: invalid continuation byte
	
	Traceback (most recent call last):
	  File "site-packages\calibre\gui2\device.py", line 86, in run
	  File "site-packages\calibre\gui2\device.py", line 490, in _books
	  File "C:\Users\Isis\AppData\Local\Temp\calibre_8snj0r\zgtw9f_ios_local_db\Marvin_overlays.py", line 435, in books
	  File "calibre_plugins.ios_reader_apps.__init__", line 1392, in _log_metrics
	UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 58: invalid continuation byte

DEBUG:  180.7 iOSReaderApp:eject() 
DEBUG:  183.5 iOSReaderApp:is_usb_connected_windows(iDevice physically connected, but ejected) 
DEBUG:  183.5 iOSReaderApp:is_usb_connected_windows(iDevice physically connected, but ejected) 
DEBUG:  183.5 iOSReaderApp:post_yank_cleanup() 
DEBUG:  185.5 iOSReaderApp:shutdown() 
DEBUG:  185.5 iOSReaderApp:eject() 
DEBUG:  186.8 iOSReaderApp:shutdown() 
DEBUG:  186.8 iOSReaderApp:eject() 

Thanks for any suggestions =)

P.S. : Apologies for my possibly bad English language...

**Comment by Philantrop** [comment]
If you're still seeing this issue, please re-open this report.
