### ISSUE TITLE
Cannot get Marvin XD & ios Reader applications plug-ins to work

### ISSUE THREAD

**Issue by dkeefe4** [Philantrop/calibre-ios-reader-applications#102]
Type of device:  iPad 4th generation, TWC

calibre 1.48 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.5
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
USB devices on system:
[u'usb\\vid_0a5c&pid_21e8&rev_0112',
 u'usb\\vid_1ea7&pid_0002&rev_0200&mi_00',
 u'usb\\vid_05e3&pid_0608&rev_3298',
 u'usb\\vid_0424&pid_2412&rev_0;;2',
 u'usb\\vid_046d&pid_c52b&rev_2400',
 u'usb\\vid_05ac&pid_820b&rev_0100',
 u'usb\\vid_05ac&pid_8511&rev_7229&mi_02',
 u'usb\\root_hub20&vid8086&pid1e26&rev0004',
 u'usb\\vid_046d&pid_c52b&rev_2400&mi_00',
 u'usb\\vid_0a5c&pid_4500&rev_0100',
 u'usb\\vid_1f44&pid_0050&rev_06:6',
 u'usb\\vid_1ea7&pid_0002&rev_0200&mi_01',
 u'usb\\vid_067b&pid_2305&rev_0202',
 u'usb\\vid_0424&pid_2514&rev_0;;3',
 u'usb\\vid_046d&pid_c52b&rev_2400&mi_01',
 u'usb\\vid_05ac&pid_12ab&rev_0402',
 u'usb\\vid_0c76&pid_1607&rev_0100&mi_03',
 u'usb\\vid_2109&pid_2812&rev_9040',
 u'usb\\vid_05ac&pid_820a&rev_0100',
 u'usb\\vid_8087&pid_0024&rev_0000',
 u'usb\\vid_2109&pid_2812&rev_9040',
 u'usb\\vid_05ac&pid_828b&rev_0079',
 u'usb\\vid_046d&pid_c52b&rev_2400&mi_02',
 u'usb\\vid_2109&pid_0812&rev_9044',
 u'usb\\vid_1058&pid_1140&rev_1012',
 u'usb\\vid_046d&pid_c50e&rev_2510',
 u'usb\\vid_1058&pid_1100&rev_0165',
 u'usb\\vid_1ea7&pid_0002&rev_0200',
 u'usb\\vid_2109&pid_0812&rev_9044',
 u'usb\\vid_8087&pid_0024&rev_0000',
 u'usb\\root_hub20&vid8086&pid1e2d&rev0004',
 u'usb\\vid_05ac&pid_8511&rev_7229&mi_00',
 u'usb\\vid_0c76&pid_1607&rev_0100',
 u'usb\\root_hub30&vid8086&pid1e31&rev0004',
 u'usb\\vid_0c76&pid_1607&rev_0100&mi_00',
 u'usb\\vid_05ac&pid_8511&rev_7229']
Traceback (most recent call last):
  File "site-packages\calibre\devices\scanner.py", line 85, in __call__
DriveError: No removable drives found
Drives detected:

No disabled plugins
Looking for devices of type: MTP_DEVICE
List of WPD PNP ids:
[u'\\\\?\\swd#wpdbusenum#{226b0f60-4bff-11e3-93a8-ec35862de113}#0000000000100000#{6ac27878-a6fa-4155-ba85-f98f491d4f33}',
 u'\\\\?\\usb#vid_05ac&pid_12ab#bb4ed9088276d0d748244891626b9453f05d173a#{6ac27878-a6fa-4155-ba85-f98f491d4f33}',
 u'\\\\?\\swd#wpdbusenum#{226b0f63-4bff-11e3-93a8-ec35862de113}#0000000000000200#{6ac27878-a6fa-4155-ba85-f98f491d4f33}']
MTP device: \\?\usb#vid_05ac&pid_12ab#bb4ed9088276d0d748244891626b9453f05d173a#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
{'device_version': u'7.1.2',
 'friendly_name': u'Apple iPad',
 'has_bulk_properties': True,
 'has_storage': True,
 'manufacturer_name': u'Apple Inc.',
 'model_name': u'Apple iPad',
 'protocol': u'MTP: 1.00',
 'serial_number': u'DMPLMDP3F4YJ',
 'storage': [{'capacity': 31708938240L,
              'capacity_objects': 0L,
              'description': u'Internal Storage',
              'filesystem': u'DCF',
              'free_objects': 2654L,
              'free_space': 3981324288L,
              'id': u's10001',
              'name': u'Internal Storage',
              'rw': True,
              'type': u'fixed_ram'}],
 'type': 'unknown'}
Not a suitable MTP device, ignoring

No suitable MTP devices found
 
Looking for devices...
	u'usb\\vid_05ac&pid_12ab&rev_0402'
 
Devices possibly connected: None

**Comment by Philantrop** [comment]
No response, closing.
