### ISSUE TITLE
Marvin Free Won't Connect To Calibre

### ISSUE THREAD

**Issue by sweetbabylee** [Philantrop/calibre-ios-reader-applications#103]
Calibre 1.48 - English
Windows 7 - 32-bit
iTunes 11.3.1.2
Marvin Free 2.7.2
Preferred reader selected - Marvin
iPad 4 - Lan

Marvin will not connect on iPad.  Below is the debug from Calibre.  iTunes does detect the ipad and there is only one device connected
Thanks

calibre 1.48  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.5
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
USB devices on system:
[u'usb\\root_hub&vid8086&pid2935&rev0003',
 u'usb\\root_hub&vid8086&pid2937&rev0003',
 u'usb\\root_hub&vid8086&pid2936&rev0003',
 u'usb\\root_hub&vid8086&pid2938&rev0003',
 u'usb\\root_hub&vid8086&pid2934&rev0003',
 u'usb\\root_hub&vid8086&pid2939&rev0003',
 u'usb\\root_hub20&vid8086&pid293c&rev0003',
 u'usb\\root_hub20&vid8086&pid293a&rev0003',
 u'usb\\vid_03f0&pid_171d&rev_0100',
 u'usb\\vid_0408&pid_03ba&rev_0109',
 u'usb\\vid_0408&pid_03ba&rev_0109&mi_00',
 u'usb\\vid_046d&pid_c517&rev_3810',
 u'usb\\vid_046d&pid_c517&rev_3810&mi_00',
 u'usb\\vid_046d&pid_c517&rev_3810&mi_01',
 u'usb\\vid_05ac&pid_12ab&rev_0340',
 u'usb\\vid_05ac&pid_12ab&rev_0340&mi_00',
 u'usb\\vid_138a&pid_0001&rev_0372']
Traceback (most recent call last):
  File "site-packages\calibre\devices\scanner.py", line 85, in __call__
DriveError: No removable drives found
Drives detected:

No disabled plugins
Looking for devices of type: MTP_DEVICE
List of WPD PNP ids:
[u'\\\\?\\usb#vid_05ac&pid_12ab&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}']
MTP device: \\?\usb#vid_05ac&pid_12ab&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
{'device_version': u'7.1.2',
 'friendly_name': u'Apple iPad',
 'has_bulk_properties': True,
 'has_storage': True,
 'manufacturer_name': u'Apple Inc.',
 'model_name': u'Apple iPad',
 'protocol': u'MTP: 1.00',
 'serial_number': u'DLXJNMTLF182',
 'storage': [{'capacity': 15854469120L,
              'capacity_objects': 0L,
              'description': u'Internal Storage',
              'filesystem': u'DCF',
              'free_objects': 5546L,
              'free_space': 8320000000L,
              'id': u's10001',
              'name': u'Internal Storage',
              'rw': True,
              'type': u'fixed_ram'}],
 'type': 'unknown'}
Not a suitable MTP device, ignoring

No suitable MTP devices found
 
Looking for devices...
	u'usb\\vid_0408&pid_03ba&rev_0109'
	u'usb\\vid_0408&pid_03ba&rev_0109&mi_00'
	u'usb\\vid_05ac&pid_12ab&rev_0340'
 
Devices possibly connected: None

**Comment by Philantrop** [comment]
Support for this model has been added quite some time ago.
