### ISSUE TITLE
Support for Recitator

### ISSUE THREAD

**Issue by maziac** [Philantrop/calibre-ios-reader-applications#116]
Hi,

I'm currently releasing a new App in the App store called 'Recitator' which reads books via Text-To-Speech. (The app is currently under review in the app store).
I would like to add support for Calibre as well and what I have read from the Readme it should be quite easy since my app is monitoring the Documents folder like the GoodReader app.

I would really like to test this and from what I understood for a test it could be as simple for me as to exchange the GoodReader Bundle id with the one of my app.

Could you tell me where I could do that. I.e. what file(s) should I touch to exchange this bundle id.
I know that this is just a dirty hack, but I just want to get a feeling for the feasibility.

Best regards,
Thomas

**Comment by Philantrop** [comment]
I won't be adding support for any new apps myself. Pull requests are welcome.
