### ISSUE TITLE
Calibre insists on converting PDFs for ibooks

### ISSUE THREAD

**Issue by ichbindasauge** [Philantrop/calibre-ios-reader-applications#129]
I have followed all the instructions. When I try to send a PDF to ibooks, calibre asks: "Auto convert the following books before uploading to the device?" If I answer "No" the book does not get transferred.

Epubs are fine. In the plugin settings both formats are checked (I have repeatedly checked and unchecked PDFs in there). Sending books using the connecting to itunes method works fine, including for PDFs.

Newest versions of itunes, calibre (set to english language) and plugin.
Windows 8.1 64
(but in the past I had the same problem with Windows 7 32)

I have tried with ipad 2 Wifi and iphone 5s, both on iOS7

It might be a problem with my calibre installation. I have had this problem for quite a while. This is a new installation, but with a transferred configuration folder from the previous computer. I have repeatedly uninstalled the plugin (and manually deleted the related files as in the instructions) and reinstalled.

Any idea?

Thanks,

Bernhard

**Comment by Philantrop** [comment]
If you're still seeing this issue, please re-open this report.
