### ISSUE TITLE
Device Not Recognised: Win 7 64 bit, Ipad 3, iOS 8.1, Calibre V2.7

### ISSUE THREAD

**Issue by docraj** [Philantrop/calibre-ios-reader-applications#146]
calibre 2.7 [64bit]  isfrozen: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.8
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: Author Book Count && FictionDB && Barnes & Noble && eReader PDB 2 PML && Quality Check && Search The Internet && Reading List && Goodreads && Fantastic Fiction && View Manager && Similar Stories && Find Duplicates && Manage Series && EpubSplit && Count Pages && Open With && iOS reader applications
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 292, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 152, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.ios_reader_apps.config", line 26, in <module>
  File "D:\My Documents\My eBooks\Calibre\_Preferences\plugins\iOS_reader_applications_resources\widgets\main_ui.py", line 10, in <module>
ImportError: No module named PyQt4
calibre 2.7 [64bit]  isfrozen: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.8
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: Count Pages && Author Book Count && Barnes & Noble && Open With && Goodreads && Fantastic Fiction && FictionDB && View Manager && EpubSplit && Search The Internet && eReader PDB 2 PML && Similar Stories && Manage Series && Quality Check && Reading List && Find Duplicates
USB devices on system:
[u'usb\\root_hub&vid8086&pid3a34&rev0000',
 u'usb\\root_hub&vid8086&pid3a38&rev0000',
 u'usb\\root_hub&vid8086&pid3a35&rev0000',
 u'usb\\root_hub&vid8086&pid3a39&rev0000',
 u'usb\\root_hub&vid8086&pid3a36&rev0000',
 u'usb\\root_hub&vid8086&pid3a37&rev0000',
 u'usb\\root_hub20&vid8086&pid3a3a&rev0000',
 u'usb\\root_hub20&vid8086&pid3a3c&rev0000',
 u'usb\\vid_0424&pid_2514&rev_0;;3',
 u'usb\\vid_0424&pid_2640&rev_0000',
 u'usb\\vid_0424&pid_4064&rev_0190',
 u'usb\\vid_045e&pid_075d&rev_0105',
 u'usb\\vid_045e&pid_075d&rev_0105&mi_00',
 u'usb\\vid_045e&pid_075d&rev_0105&mi_02',
 u'usb\\vid_046d&pid_c52b&rev_1201',
 u'usb\\vid_046d&pid_c52b&rev_1201&mi_00',
 u'usb\\vid_046d&pid_c52b&rev_1201&mi_01',
 u'usb\\vid_046d&pid_c52b&rev_1201&mi_02',
 u'usb\\vid_05a7&pid_1020&rev_0100',
 u'usb\\vid_05a7&pid_1020&rev_0100&mi_00',
 u'usb\\vid_05a7&pid_1020&rev_0100&mi_02',
 u'usb\\vid_05ac&pid_12a6&rev_0330',
 u'usb\\vid_05ac&pid_12a6&rev_0330&mi_00',
 u'usb\\vid_1058&pid_0830&rev_1059',
 u'usb\\vid_1737&pid_0071&rev_0101']
Unable to get free space for drive: I
(21, 'GetDiskFreeSpaceEx', 'The device is not ready.')
Drives detected:

Disabled plugins: ITUNES
 
Looking for devices of type: MTP_DEVICE
List of WPD PNP ids:
[u'\\\\?\\usb#vid_05ac&pid_12a6&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}',
 u'\\\\?\\wpdbusenumroot#umb#2&37c186b&0&storage#volume#_??_usbstor#disk&ven_generic&prod_ultra_hs-sd#mmc&rev_1.90#000000264001&0##{6ac27878-a6fa-4155-ba85-f98f491d4f33}']
MTP device: \\?\usb#vid_05ac&pid_12a6&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
{'device_version': u'8.1',
 'friendly_name': u'Apple iPad',
 'has_bulk_properties': True,
 'has_storage': True,
 'manufacturer_name': u'Apple Inc.',
 'model_name': u'Apple iPad',
 'protocol': u'MTP: 1.00',
 'serial_number': u'DLXH8HJBDVGJ',
 'storage': [{'capacity': 63417876480L,
              'capacity_objects': 0L,
              'description': u'Internal Storage',
              'filesystem': u'DCF',
              'free_objects': 15959L,
              'free_space': 23938850816L,
              'id': u's10001',
              'name': u'Internal Storage',
              'rw': True,
              'type': u'fixed_ram'}],
 'type': 'unknown'}
Not a suitable MTP device, ignoring

No suitable MTP devices found
 
Looking for devices...
 
Devices possibly connected: None

**Comment by Philantrop** [comment]
If you're still seeing this issue, please re-open this report.
