### ISSUE TITLE
Unable to connect to iDevice

### ISSUE THREAD

**Issue by Ishtiaque1** [Philantrop/calibre-ios-reader-applications#147]
My ipad mini 2 with Marvin does not seem to connect to calirbe. I have both "iOs Reader application" and "Marvin XD" installed in my pc. 

The version of calibre you are using: 2.8
Calibre's language setting (available in Preferences | Interface | Look and Feel | Choose language): English
Operating system: Windows 7, 32-bit
The version of iTunes installed on your system: Windows 12.0.1
The version of the plugin installed: iOs Reader application version 1.4.4. Marvin XD version1.2.4.
The preferred reader application selected in the configuration dialog: Marvin
A description of your iDevice including cellular technology/provider, if applicable: iPad mini 2nd gen 32GB wifi.
A description of the problem: Whenever I connect my ipad to the laptop while the Calibre app is open in the pc and Marvin app in calibre connection mode is opern in the ipad the message "Unable to connect to iDevice" with the obtions "Ok" and "copy to clipboard" flashes repeatedly. clicking either of the two options does not stop the message from flashing back again.
The specific steps to recreate the problem: Connecting my ipad to the laptop while the Calibre app is open in the pc and Marvin app in calibre connection mode is opern in the ipad.

I am pasting the Calibre debug log below. Thanks in advance.

calibre Debug log
calibre 2.8  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.8
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
DEBUG:    0.0 iOSReaderApp:initialize(v1.4.4) 
DEBUG:    0.0 iOSReaderApp:compile_ui() 
DEBUG:    0.2 iOSReaderApp:_init_prefs(prefs created under v1.4.4) 
DEBUG:    0.2  debug_libimobiledevice: False
DEBUG:    0.2  debug_plugin: True
DEBUG:    0.2  development_mode: False
DEBUG:    0.2  device_booklist_cache_limit: 10
DEBUG:    0.2  device_booklist_caching: False
DEBUG:    0.2  kindle_enabled_formats: [u'MOBI', u'PDF']
DEBUG:    0.2  kindle_supported_formats: [u'MOBI', u'PDF']
DEBUG:    0.2  marvin_edit_collections_cb: False
DEBUG:    0.2  marvin_protect_rb: True
DEBUG:    0.2  marvin_replace_rb: False
DEBUG:    0.2  marvin_update_rb: False
DEBUG:    0.2  plugin_diagnostics: True
DEBUG:    0.2  preferred_reader_app: u'Marvin'
DEBUG:    0.2 iOSReaderApp:_get_connected_device_info() 
DEBUG:    1.3  No connected iDevices
Successfully initialized third party plugins: iOS reader applications && Marvin XD
Starting up...
Failed to read metadata from font file: c:\windows\fonts\chameli.ttf tuple index out of range
DEBUG:    5.9 iOSReaderApp:startup() 
DEBUG:    5.9 iOSReaderApp:_dump_installed_plugins() 
DEBUG:    5.9  plugin     author           version
DEBUG:    5.9  ---------  ---------------  -----
DEBUG:    5.9  Marvin XD  Wulf C. Krueger  1.2.4 
DEBUG:    5.9  ---------  ---------------  -----
Started up in 21.51 seconds with 144 books
DEBUG:   42.5 iOSReaderApp:_get_connected_device_info() 
DEBUG:   46.9 libiMobileDevice:connect_idevice(ERROR: libiMobileDevice:_lockdown_start_service(): PLIST_ERROR) 
Traceback (most recent call last):
  File "calibre_plugins.ios_reader_apps.__init__", line 1202, in _get_connected_device_info
libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.'
DEBUG:   46.9 iOSReaderApp:_get_connected_device_info(ERROR: libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.') 
DEBUG:   49.2 iOSReaderApp:_get_connected_device_info() 
DEBUG:   51.6 libiMobileDevice:connect_idevice(ERROR: libiMobileDevice:_lockdown_start_service(): PLIST_ERROR) 
Traceback (most recent call last):
  File "calibre_plugins.ios_reader_apps.__init__", line 1202, in _get_connected_device_info
libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.'
DEBUG:   51.6 iOSReaderApp:_get_connected_device_info(ERROR: libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.') 
DEBUG:   53.6 iOSReaderApp:_get_connected_device_info() 
DEBUG:   55.9 libiMobileDevice:connect_idevice(ERROR: libiMobileDevice:_lockdown_start_service(): PLIST_ERROR) 
Traceback (most recent call last):
  File "calibre_plugins.ios_reader_apps.__init__", line 1202, in _get_connected_device_info
libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.'
DEBUG:   55.9 iOSReaderApp:_get_connected_device_info(ERROR: libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.') 
DEBUG:   57.9 iOSReaderApp:_get_connected_device_info() 
DEBUG:   60.3 libiMobileDevice:connect_idevice(ERROR: libiMobileDevice:_lockdown_start_service(): PLIST_ERROR) 
Traceback (most recent call last):
  File "calibre_plugins.ios_reader_apps.__init__", line 1202, in _get_connected_device_info
libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.'
DEBUG:   60.3 iOSReaderApp:_get_connected_device_info(ERROR: libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.') 
DEBUG:   62.4 iOSReaderApp:_get_connected_device_info() 
DEBUG:   64.8 libiMobileDevice:connect_idevice(ERROR: libiMobileDevice:_lockdown_start_service(): PLIST_ERROR) 
Traceback (most recent call last):
  File "calibre_plugins.ios_reader_apps.__init__", line 1202, in _get_connected_device_info
libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.'
DEBUG:   64.8 iOSReaderApp:_get_connected_device_info(ERROR: libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.') 
DEBUG:   66.8 iOSReaderApp:_get_connected_device_info() 
DEBUG:   69.1 libiMobileDevice:connect_idevice(ERROR: libiMobileDevice:_lockdown_start_service(): PLIST_ERROR) 
Traceback (most recent call last):
  File "calibre_plugins.ios_reader_apps.__init__", line 1202, in _get_connected_device_info
libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.'
DEBUG:   69.1 iOSReaderApp:_get_connected_device_info(ERROR: libiMobileDeviceException: u'Unable to connect to iDevice. If you are updating, disconnect your iDevice first.') 
DEBUG:   71.1 iOSReaderApp:_get_connected_device_info()

**Comment by Philantrop** [comment]
If you're still seeing this issue, please re-open this report.
