### ISSUE TITLE
upgraded to ios 8.2, calibre won't connect

### ISSUE THREAD

**Issue by akita328** [Philantrop/calibre-ios-reader-applications#148]
MacOS 10.6.8, Calibre 1.48
when iPad mini retina was on iOS 7.1.2, everything connected fine.

updated to iOS 8.2, now it will not connect.
1.  first it could not recognize the iDevice
2.  then it said iOS reader application is not installed
3.  I try re-installing, but after restart of calibre, setting preferences, and then reconnecting iPad, the iOS reader plug-in is no longer there (disappears from the plugin list)
4.  tried to delete ~/Library/Preferences/Calibre folder for a fresh start..  same thing.  install iOS reader, set it up, and as soon as I connect iPad, the plug in disappears, iDevice will not connect..

**Comment by Philantrop** [comment]
If you're still seeing this issue, please provide the all the information described in https://github.com/Philantrop/calibre-ios-reader-applications/issues/1 and re-open this report.
