### ISSUE TITLE
Can't add books to iDevice via plugin after upgrade to iTunes 12

### ISSUE THREAD

**Issue by PeterBeckley** [Philantrop/calibre-ios-reader-applications#150]
Using Calibre 2.10 and haven't changed configuration of either it or iTunes, but did verify the configuration of iTunes/iDevice (iPad 1stGen) based upon plugin thread on Mobileread. 

Also tried connecting through built-in "Connect to iTunes", and that failed as well. Both act as if there is a new device/itunes library rather than reading the iDevice contents. Once Calibre is restarted, this "library" is empty again.

Interestingly I now have an ebook on my iDevice called "Tracer".

**Comment by Philantrop** [comment]
If you're still seeing this issue, please provide the all the information described in https://github.com/Philantrop/calibre-ios-reader-applications/issues/1 and re-open this report.
