### ISSUE TITLE
iPad Air 2, Verizon; Calibre not recognizing device

### ISSUE THREAD

**Issue by pmarking** [Philantrop/calibre-ios-reader-applications#152]
calibre 2.10  isfrozen: True is64bit: True
Darwin-14.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.0.0', 'Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64')
Python 2.7.8
OSX: ('10.10', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: Marvin XD && iOS reader applications && Find Duplicates && Manage Series
USB devices on system:
[['0x5ac', '0x1105', '0x120', u'Apple Inc.', u'Display Audio', u'74040516'],
 ['0x5ac',
  '0x8215',
  '0x208',
  u'Apple Inc.',
  u'Bluetooth USB Host Controller',
  u'7CC3A156254A'],
 ['0x152d',
  '0x539',
  '0x2805',
  u'JMicron',
  u'USB to ATA/ATAPI Bridge',
  u'000000000000'],
 ['0x56a',
  '0x84',
  '0x111',
  u'Wacom Co.,Ltd.',
  u'Wacom Wireless Receiver',
  None],
 ['0x56a', '0x315', '0x100', u'Wacom Co.,Ltd.', u'Intuos5 touch M', None],
 ['0x46d', '0xc52b', '0x2400', u'Logitech', u'USB Receiver', None],
 ['0x3f0',
  '0x2917',
  '0x100',
  u'Hewlett-Packard',
  u'hp LaserJet 2420',
  u'CNGKB45528\x00\x00'],
 ['0x4a9', '0x176b', '0x102', u'Canon', u'MX920 series', u'30A806'],
 ['0x5ac',
  '0x12ab',
  '0x504',
  u'Apple Inc.',
  u'iPad',
  u'945928fec46f9b7e62a7a4b9591bf14f04ea9093'],
 ['0x11b0', '0x6178', '0x9745', u'G5X', u'PRO Reader', u'A00000007'],
 ['0x5ac',
  '0x9226',
  '0x299',
  u'Apple Inc.',
  u'Apple LED Cinema Display',
  None]]

No disabled plugins
Looking for devices of type: MTP_DEVICE
No MTP devices connected to system
 
Looking for devices...
 
Devices possibly connected: None 
 
IOREG Output
Output from mount:
'/dev/disk2 on / (hfs, local, journaled)\ndevfs on /dev (devfs, local, nobrowse)\n/dev/disk3s2 on /Volumes/DATA (hfs, local, journaled)\nmap -hosts on /net (autofs, nosuid, automounted, nobrowse)\nmap auto_home on /home (autofs, automounted, no browse)\n'

Output from osx_get_usb_drives:
[]

**Comment by Philantrop** [comment]
Fixed since Version 1.4.6 - 1 January 2015
