### ISSUE TITLE
Calibre 2.11 not recognizing iPad 2 running iOS 8.1.1

### ISSUE THREAD

**Issue by ScottUrman** [Philantrop/calibre-ios-reader-applications#153]
calibre 2.11 [64bit]  isfrozen: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.8
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: iOS reader applications
USB devices on system:
[u'usb\\root_hub20&vid8086&pid1c2d&rev0004',
 u'usb\\root_hub20&vid8086&pid1c26&rev0004',
 u'usb\\vid_0424&pid_2504&rev_0001',
 u'usb\\vid_05ac&pid_12a2&rev_0220',
 u'usb\\vid_05ac&pid_12a2&rev_0220&mi_00',
 u'usb\\vid_0a5c&pid_5801&rev_0101',
 u'usb\\vid_0a5c&pid_5801&rev_0101&mi_00',
 u'usb\\vid_0a5c&pid_5801&rev_0101&mi_01',
 u'usb\\vid_413c&pid_1005&rev_5900',
 u'usb\\vid_413c&pid_2011&rev_5900',
 u'usb\\vid_413c&pid_2011&rev_5900&mi_00',
 u'usb\\vid_413c&pid_2011&rev_5900&mi_01',
 u'usb\\vid_413c&pid_2513&rev_:005',
 u'usb\\vid_413c&pid_2513&rev_:005',
 u'usb\\vid_413c&pid_3012&rev_4301',
 u'usb\\vid_413c&pid_8187&rev_0517',
 u'usb\\vid_8087&pid_0024&rev_0000',
 u'usb\\vid_8087&pid_0024&rev_0000']
Traceback (most recent call last):
  File "site-packages\calibre\devices\scanner.py", line 85, in __call__
DriveError: No removable drives found
Drives detected:

No disabled plugins
Looking for devices of type: MTP_DEVICE
List of WPD PNP ids:
[u'\\\\?\\usb#vid_05ac&pid_12a2&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}']
MTP device: \\?\usb#vid_05ac&pid_12a2&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
{'device_version': u'8.1.1',
 'friendly_name': u'Apple iPad',
 'has_bulk_properties': True,
 'has_storage': True,
 'manufacturer_name': u'Apple Inc.',
 'model_name': u'Apple iPad',
 'protocol': u'MTP: 1.00',
 'serial_number': u'DLXFH6LKDFJ2',
 'storage': [{'capacity': 31943819264L,
              'capacity_objects': 0L,
              'description': u'Internal Storage',
              'filesystem': u'DCF',
              'free_objects': 10433L,
              'free_space': 15650185216L,
              'id': u's10001',
              'name': u'Internal Storage',
              'rw': True,
              'type': u'fixed_ram'}],
 'type': 'unknown'}
Not a suitable MTP device, ignoring

No suitable MTP devices found
 
Looking for devices...
	u'usb\\vid_05ac&pid_12a2&rev_0220'
 
Devices possibly connected: None

**Comment by Philantrop** [comment]
If you're still seeing this issue, please re-open this report.
