### ISSUE TITLE
Calibre 2.1.1 doesnt see ibooks as choice for ipad

### ISSUE THREAD

**Issue by adrianschm** [Philantrop/calibre-ios-reader-applications#155]
Hi,

followed all your instructions to setup calibre to work with ipad 4. using OSX8.1.1 and mac running 
Mavericks. got to part where you say to go to Preferences/advanced/plugins/ios.../ and double clicked to customize plugin.  on top is has the drop down menu (preffered IOS reader application) with Good Reader/Good Reader 4/Kindle/Marvin. there is no choice for Ibooks. Ive looked thru all your documentation and rechecked all Itunes and Calibre configuration instructions and cant understand why it doesnt give an option for Prefernces.  BTW works fine with Marvin and Itunes not with Ibooks app on Ipad.  Help!

**Comment by Philantrop** [comment]
cf. http://www.mobileread.com/forums/showthread.php?t=241143

"iBooks for iOS
This plugin does not work with iBooks under OS X 10.9 (Mavericks)."
