### ISSUE TITLE
Cannot connect to ipad air 2.

### ISSUE THREAD

**Issue by ssarangi** [Philantrop/calibre-ios-reader-applications#158]
The version of calibre you are using : Calibre 2.0 - 32bit application
Calibre's language setting (available in Preferences | Interface | Look and Feel | Choose language) : English
Your operating system, and 32- or 64-bit, if applicable. Windows 8, 64-bit 
The version of iTunes installed on your system (OS X and Windows). - 12.0.1.26
The version of the plugin installed - 1.4.4
The preferred reader application selected in the configuration dialog - Marvin
A description of your iDevice including cellular technology/provider, if applicable - N/A
A description of the problem: Marvin application says "Marvin not connected" even though calibre connector is running on marvin

Log:
------
calibre 2.12  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.8
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
DEBUG:    0.0 iOSReaderApp:initialize(v1.4.4) 
DEBUG:    0.1 iOSReaderApp:compile_ui() 
DEBUG:    0.8 iOSReaderApp:_init_prefs(prefs created under v1.4.4) 
DEBUG:    0.8  debug_libimobiledevice: True
DEBUG:    0.8  debug_plugin: True
DEBUG:    0.8  development_mode: False
DEBUG:    0.8  device_booklist_cache_limit: 10
DEBUG:    0.8  device_booklist_caching: False
DEBUG:    0.8  kindle_enabled_formats: [u'MOBI', u'PDF']
DEBUG:    0.8  kindle_supported_formats: [u'MOBI', u'PDF']
DEBUG:    0.8  marvin_edit_collections_cb: True
DEBUG:    0.8  marvin_protect_rb: False
DEBUG:    0.8  marvin_replace_rb: True
DEBUG:    0.8  marvin_update_rb: False
DEBUG:    0.8  plugin_diagnostics: True
DEBUG:    0.8  preferred_reader_app: u'Marvin'
DEBUG:    0.8 libiMobileDevice:__init__() 
DEBUG:    0.8 libiMobileDevice:load_library(Windows) 
DEBUG:    0.8   libimobiledevice loaded from 'libimobiledevice.dll'
DEBUG:    0.8   libplist loaded from 'libplist.dll'
DEBUG:    0.8 iOSReaderApp:_get_connected_device_info() 
DEBUG:    0.8 libiMobileDevice:get_device_list() 
DEBUG:    0.8 libiMobileDevice:_idevice_get_device_list() 
DEBUG:    1.0   ['6fefc85f5bc782799620c2af1373d7833eb0d2dd']
DEBUG:    1.0 libiMobileDevice:connect_idevice() 
DEBUG:    1.0 libiMobileDevice:_idevice_new() 
DEBUG:    1.1         conn_type: CONNECTION_USBMUXD
DEBUG:    1.1              udid: 6fefc85f5bc782799620c2af1373d7833eb0d2dd
DEBUG:    1.1 libiMobileDevice:_lockdown_client_new_with_handshake() 
DEBUG:    2.7 libiMobileDevice:_lockdown_get_device_name() 
DEBUG:    2.7       device_name: Satyajit's iPad
DEBUG:    2.7 libiMobileDevice:_lockdown_start_service(com.apple.mobile.installation_proxy) 
DEBUG:    2.7 libiMobileDevice:get_preferences() 
DEBUG:    2.7 libiMobileDevice:_lockdown_get_value() 
DEBUG:    2.8 libiMobileDevice:disconnect_idevice(Satyajit's iPad) 
DEBUG:    2.8   device already disconnected
DEBUG:    2.8 libiMobileDevice:mount_ios_media_folder() 
DEBUG:    2.8 libiMobileDevice:_idevice_new() 
DEBUG:    2.9         conn_type: CONNECTION_USBMUXD
DEBUG:    2.9              udid: 6fefc85f5bc782799620c2af1373d7833eb0d2dd
DEBUG:    2.9 libiMobileDevice:_lockdown_client_new_with_handshake() 
DEBUG:    3.2 libiMobileDevice:_lockdown_start_service(com.apple.afc) 
DEBUG:    3.2 libiMobileDevice:_afc_client_new() 
DEBUG:    3.2 libiMobileDevice:_lockdown_client_free() 
DEBUG:    3.3 libiMobileDevice:_afc_get_device_info() 
DEBUG:    3.3       FSBlockSize: 4096
DEBUG:    3.3             Model: iPad5,3
DEBUG:    3.3      FSTotalBytes: 12854226944
DEBUG:    3.3       FSFreeBytes: 10366128128
DEBUG:    3.3 libiMobileDevice:_afc_client_free() 
DEBUG:    3.3 libiMobileDevice:_idevice_free() 
DEBUG:    3.3  mounting 'com.appstafarian.MarvinIP'
DEBUG:    3.3 libiMobileDevice:mount_ios_app(com.appstafarian.MarvinIP) 
DEBUG:    3.3 libiMobileDevice:_idevice_new() 
DEBUG:    3.3         conn_type: CONNECTION_USBMUXD
DEBUG:    3.3              udid: 6fefc85f5bc782799620c2af1373d7833eb0d2dd
DEBUG:    3.3 libiMobileDevice:_lockdown_client_new_with_handshake() 
DEBUG:    3.6 libiMobileDevice:_lockdown_get_device_name() 
DEBUG:    3.7       device_name: Satyajit's iPad
DEBUG:    3.7 libiMobileDevice:_lockdown_start_service(com.apple.mobile.house_arrest) 
DEBUG:    3.7 libiMobileDevice:_house_arrest_client_new() 
DEBUG:    3.7 libiMobileDevice:_house_arrest_send_command(command=u'VendContainer' appid='com.appstafarian.MarvinIP') 
DEBUG:    3.7 libiMobileDevice:_house_arrest_get_result() 
DEBUG:    3.8             ERROR: InstallationLookupFailed
DEBUG:    3.8 libiMobileDevice:mount_ios_app(com.appstafarian.MarvinIP: InstallationLookupFailed) 
DEBUG:    3.8 libiMobileDevice:disconnect_idevice(Satyajit's iPad) 
DEBUG:    3.8   device already disconnected
DEBUG:    3.8 libiMobileDevice:mount_ios_app(unable to mount 'com.appstafarian.MarvinIP') 
DEBUG:    3.8  mounting 'com.appstafarian.MarvinIP-free'
DEBUG:    3.8 libiMobileDevice:mount_ios_app(com.appstafarian.MarvinIP-free) 
DEBUG:    3.8 libiMobileDevice:_idevice_new() 
DEBUG:    3.8         conn_type: CONNECTION_USBMUXD
DEBUG:    3.8              udid: 6fefc85f5bc782799620c2af1373d7833eb0d2dd
DEBUG:    3.8 libiMobileDevice:_lockdown_client_new_with_handshake() 
DEBUG:    4.1 libiMobileDevice:_lockdown_get_device_name() 
DEBUG:    4.2       device_name: Satyajit's iPad
DEBUG:    4.2 libiMobileDevice:_lockdown_start_service(com.apple.mobile.house_arrest) 
DEBUG:    4.2 libiMobileDevice:_house_arrest_client_new() 
DEBUG:    4.2 libiMobileDevice:_house_arrest_send_command(command=u'VendContainer' appid='com.appstafarian.MarvinIP-free') 
DEBUG:    4.2 libiMobileDevice:_house_arrest_get_result() 
DEBUG:    4.3            STATUS: Complete
DEBUG:    4.3 libiMobileDevice:_afc_client_new_from_house_arrest_client() 
DEBUG:    4.3 libiMobileDevice:_lockdown_client_free() 
DEBUG:    4.3 libiMobileDevice:mount_ios_app('com.appstafarian.MarvinIP-free' mounted) 
DEBUG:    4.3 libiMobileDevice:disconnect_idevice(Satyajit's iPad) 
DEBUG:    4.3 libiMobileDevice:_afc_client_free() 
DEBUG:    4.3 libiMobileDevice:_house_arrest_client_free() 
DEBUG:    4.3 libiMobileDevice:_idevice_free() 
DEBUG:    4.3 iOSReaderApp:_class_reconfigure('Marvin') 
DEBUG:    4.3 iOSReaderApp:_load_reader_app_overlays('Marvin') 
DEBUG:    4.5  loading 58 overlays
DEBUG:    4.5  adding overlay '_compare_mainDb_profiles()'
DEBUG:    4.5  adding overlay '_cover_subpath()'
DEBUG:    4.5  adding overlay '_cover_to_thumb()'
DEBUG:    4.5  adding overlay '_create_cover_element()'
DEBUG:    4.5  adding overlay '_create_empty_booklist_db()'
DEBUG:    4.5  adding overlay '_create_new_book()'
DEBUG:    4.5  adding overlay '_dehydrate_booklist()'
DEBUG:    4.5  adding overlay '_establish_local_booklist_db_path()'
DEBUG:    4.5  adding overlay '_evaluate_original_cover()'
DEBUG:    4.5  adding overlay '_evaluate_replaceable_cover()'
DEBUG:    4.5  adding overlay '_get_field_items()'
DEBUG:    4.5  adding overlay '_get_opf_tree()'
DEBUG:    4.5  adding overlay '_get_opf_xml()'
DEBUG:    4.5  adding overlay '_initialize_overlay()'
DEBUG:    4.5  adding overlay '_localize_booklist_db()'
DEBUG:    4.5  adding overlay '_localize_database_path()'
DEBUG:    4.5  adding overlay '_parse_version()'
DEBUG:    4.5  adding overlay '_parse_xml()'
DEBUG:    4.5  adding overlay '_profile_db()'
DEBUG:    4.5  adding overlay '_rehydrate_booklist()'
DEBUG:    4.5  adding overlay '_remove_existing_copy()'
DEBUG:    4.5  adding overlay '_report_upload_results()'
DEBUG:    4.5  adding overlay '_reset_ios_connection()'
DEBUG:    4.5  adding overlay '_restore_from_snapshot()'
DEBUG:    4.6  adding overlay '_schedule_metadata_update()'
DEBUG:    4.6  adding overlay '_snapshot_booklist()'
DEBUG:    4.6  adding overlay '_stage_command_file()'
DEBUG:    4.6  adding overlay '_update_epub_metadata()'
DEBUG:    4.6  adding overlay '_validate_dehydrated_booklist()'
DEBUG:    4.6  adding overlay '_wait_for_command_completion()'
DEBUG:    4.6  adding overlay '_watchdog_timed_out()'
DEBUG:    4.6  adding overlay '_xform_metadata_via_plugboard()'
DEBUG:    4.6  adding overlay 'add_books_to_metadata()'
DEBUG:    4.6  adding overlay 'books()'
DEBUG:    4.6  adding overlay 'can_handle()'
DEBUG:    4.6  adding overlay 'can_handle_windows()'
DEBUG:    4.6  adding overlay 'delete_books()'
DEBUG:    4.6  adding overlay 'eject()'
DEBUG:    4.6  adding overlay 'from_json()'
DEBUG:    4.6  adding overlay 'get_busy_flag()'
DEBUG:    4.6  adding overlay 'get_cc_mapping()'
DEBUG:    4.6  adding overlay 'get_file()'
DEBUG:    4.6  adding overlay 'guess_type()'
DEBUG:    4.6  adding overlay 'is_usb_connected()'
DEBUG:    4.6  adding overlay 'is_usb_connected_windows()'
DEBUG:    4.6  adding overlay 'post_yank_cleanup()'
DEBUG:    4.6  adding overlay 'prepare_addable_books()'
DEBUG:    4.6  adding overlay 'remove_books_from_metadata()'
DEBUG:    4.6  adding overlay 'set_busy_flag()'
DEBUG:    4.6  adding overlay 'set_cc_mapping()'
DEBUG:    4.6  adding overlay 'shutdown()'
DEBUG:    4.6  adding overlay 'sort_key()'
DEBUG:    4.6  adding overlay 'startup()'
DEBUG:    4.6  adding overlay 'sync_booklists()'
DEBUG:    4.6  adding overlay 'thumbnail()'
DEBUG:    4.6  adding overlay 'to_json()'
DEBUG:    4.6  adding overlay 'upload_books()'
DEBUG:    4.6  adding overlay 'xml_to_unicode()'
DEBUG:    4.6 iOSReaderApp:_initialize_overlay(Marvin) 
DEBUG:    4.6  existing thumb cache at 'C:\Users\sarangis\AppData\Local\calibre-cache\Marvin\thumbs.zip'
DEBUG:    4.6  ~~~~~~~~~~~~~~~~~~~~~~~~~ switching to Marvin overlay ~~~~~~~~~~~~~~~~~~~~~~~~~~
Successfully initialized third party plugins: Marvin XD && iOS reader applications
Starting up...
DEBUG:    8.7 MarvinManagerAction:genesis(v1.2.4) 
DEBUG:    8.7 MarvinManagerAction:init_options() 
DEBUG:    8.7 AnnotationsDB:connect(db_version: 1) 
DEBUG:    8.7 MarvinManagerAction:inflate_dialog_resources() 
DEBUG:    9.0 MarvinManagerAction:compile_ui() 
DEBUG:   10.8 iOSReaderApp:startup() 
DEBUG:   10.8 iOSReaderApp:_dump_installed_plugins() 
DEBUG:   10.8  plugin     author           version
DEBUG:   10.8  ---------  ---------------  -----
DEBUG:   10.8  Marvin XD  Wulf C. Krueger  1.2.4 
DEBUG:   10.8  ---------  ---------------  -----
DEBUG:   10.8  Waiting for calibre connector...
DEBUG:   12.3 MarvinManagerAction:rebuild_menus() 
DEBUG:   12.4  Marvin not connected
Started up in 6.78 seconds with 94 books
DEBUG:  389.4 MarvinManagerAction:rebuild_menus() 
DEBUG:  389.4  Marvin not connected

**Comment by Philantrop** [comment]
Fixed since Version 1.4.6 - 1 January 2015
