### ISSUE TITLE
iPad Air 2 connection issue

### ISSUE THREAD

**Issue by Shadewing666** [Philantrop/calibre-ios-reader-applications#159]
Calibre Version: Windows 2.12 64bit
Calibre language: English
Computer OS: Windows 8.1 64bit
iTunes version: 12.0.1.26
Plugin version: 1.4.4
iOS reader: Marvin
iDevice: New (purchased today) iPad Air 2 128GB, iOS 8.1.1 Jailbreak
Problem: Calibre does not connect to Marvin on the iPad (tried both before and after Jailbreak)

-----------------------------------------------------------------------------------------------------------------------

Calibre device detection debug output:

calibre 2.12 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.8
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: Marvin XD && FanFictionDownLoader && Quality Check && iOS reader applications
USB devices on system:
[u'usb\\vid_0bc2&pid_ab31&rev_0342',
 u'usb\\vid_8087&pid_8002&rev_0005',
 u'usb\\vid_1e7d&pid_3232&rev_0100',
 u'usb\\vid_1770&pid_ef35&rev_0110',
 u'usb\\vid_174c&pid_3074&rev_0001',
 u'usb\\vid_174c&pid_3074&rev_0001',
 u'usb\\vid_8087&pid_800a&rev_0005',
 u'usb\\root_hub30&vid8086&pid8d31&rev0005',
 u'usb\\vid_0738&pid_1713&rev_0120',
 u'usb\\vid_1e7d&pid_3232&rev_0100&mi_01',
 u'usb\\vid_1e7d&pid_3232&rev_0100&mi_00',
 u'usb\\vid_174c&pid_2074&rev_0001',
 u'usb\\asmediausbd_hub&vid_1e7d&pid_2ee1&rev_3299',
 u'usb\\vid_05ac&pid_12ab&rev_0503',
 u'usb\\vid_0b05&pid_180a&rev_0112',
 u'usb\\asmediausbd_hub&vid_040e&pid_0100&rev_0000',
 u'usb\\root_hub20&vid8086&pid8d26&rev0005',
 u'usb\\root_hub20&vid8086&pid8d2d&rev0005',
 u'usb\\vid_174c&pid_2074&rev_0001']
Traceback (most recent call last):
  File "site-packages\calibre\devices\scanner.py", line 85, in __call__
DriveError: No removable drives found
Drives detected:

No disabled plugins
Looking for devices of type: MTP_DEVICE
List of WPD PNP ids:
[u'\\\\?\\swd#wpdbusenum#{43ea18e6-6246-11e4-8255-806e6f6e6963}#0000000000800000#{6ac27878-a6fa-4155-ba85-f98f491d4f33}']
No suitable MTP devices found
 
Looking for devices...
 
Devices possibly connected: None 

-------------------------------------------------------------------------------------------------

debug_log.txt

calibre 2.12 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.8
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
DEBUG:    0.0 iOSReaderApp:initialize(v1.4.4) 
DEBUG:    0.0 iOSReaderApp:compile_ui() 
DEBUG:    0.1 iOSReaderApp:_init_prefs(prefs created under v1.4.4) 
DEBUG:    0.1  cc_mappings: {u'Big HP 2': {u'marvin_collections': {u'field': u'#mm_collections', u'combobox': u'Marvin Collections'}, u'marvin_locked': {u'field': u'#mm_locked', u'combobox': u'Locked'}, u'marvin_word_count': {u'field': u'#mm_word_count', u'combobox': u'Marvin Word count'}}}
DEBUG:    0.1  debug_libimobiledevice: False
DEBUG:    0.1  debug_plugin: True
DEBUG:    0.1  development_mode: False
DEBUG:    0.1  device_booklist_cache_limit: 10
DEBUG:    0.1  device_booklist_caching: False
DEBUG:    0.1  kindle_enabled_formats: [u'MOBI', u'PDF']
DEBUG:    0.1  kindle_supported_formats: [u'MOBI', u'PDF']
DEBUG:    0.1  marvin_edit_collections_cb: True
DEBUG:    0.1  marvin_protect_rb: False
DEBUG:    0.1  marvin_replace_rb: True
DEBUG:    0.1  marvin_update_rb: False
DEBUG:    0.1  plugin_diagnostics: True
DEBUG:    0.1  preferred_reader_app: u'Marvin'
DEBUG:    0.1 iOSReaderApp:_get_connected_device_info() 
DEBUG:    1.0  mounting 'com.appstafarian.MarvinIP'
DEBUG:    1.2 iOSReaderApp:_class_reconfigure('Marvin') 
DEBUG:    1.2 iOSReaderApp:_load_reader_app_overlays('Marvin') 
DEBUG:    1.2  loading 58 overlays
DEBUG:    1.2  adding overlay '_compare_mainDb_profiles()'
DEBUG:    1.2  adding overlay '_cover_subpath()'
DEBUG:    1.2  adding overlay '_cover_to_thumb()'
DEBUG:    1.2  adding overlay '_create_cover_element()'
DEBUG:    1.2  adding overlay '_create_empty_booklist_db()'
DEBUG:    1.2  adding overlay '_create_new_book()'
DEBUG:    1.2  adding overlay '_dehydrate_booklist()'
DEBUG:    1.2  adding overlay '_establish_local_booklist_db_path()'
DEBUG:    1.2  adding overlay '_evaluate_original_cover()'
DEBUG:    1.2  adding overlay '_evaluate_replaceable_cover()'
DEBUG:    1.2  adding overlay '_get_field_items()'
DEBUG:    1.2  adding overlay '_get_opf_tree()'
DEBUG:    1.2  adding overlay '_get_opf_xml()'
DEBUG:    1.2  adding overlay '_initialize_overlay()'
DEBUG:    1.2  adding overlay '_localize_booklist_db()'
DEBUG:    1.2  adding overlay '_localize_database_path()'
DEBUG:    1.2  adding overlay '_parse_version()'
DEBUG:    1.2  adding overlay '_parse_xml()'
DEBUG:    1.2  adding overlay '_profile_db()'
DEBUG:    1.2  adding overlay '_rehydrate_booklist()'
DEBUG:    1.2  adding overlay '_remove_existing_copy()'
DEBUG:    1.2  adding overlay '_report_upload_results()'
DEBUG:    1.2  adding overlay '_reset_ios_connection()'
DEBUG:    1.2  adding overlay '_restore_from_snapshot()'
DEBUG:    1.2  adding overlay '_schedule_metadata_update()'
DEBUG:    1.2  adding overlay '_snapshot_booklist()'
DEBUG:    1.2  adding overlay '_stage_command_file()'
DEBUG:    1.2  adding overlay '_update_epub_metadata()'
DEBUG:    1.2  adding overlay '_validate_dehydrated_booklist()'
DEBUG:    1.2  adding overlay '_wait_for_command_completion()'
DEBUG:    1.2  adding overlay '_watchdog_timed_out()'
DEBUG:    1.2  adding overlay '_xform_metadata_via_plugboard()'
DEBUG:    1.2  adding overlay 'add_books_to_metadata()'
DEBUG:    1.2  adding overlay 'books()'
DEBUG:    1.2  adding overlay 'can_handle()'
DEBUG:    1.2  adding overlay 'can_handle_windows()'
DEBUG:    1.2  adding overlay 'delete_books()'
DEBUG:    1.2  adding overlay 'eject()'
DEBUG:    1.2  adding overlay 'from_json()'
DEBUG:    1.2  adding overlay 'get_busy_flag()'
DEBUG:    1.2  adding overlay 'get_cc_mapping()'
DEBUG:    1.2  adding overlay 'get_file()'
DEBUG:    1.2  adding overlay 'guess_type()'
DEBUG:    1.2  adding overlay 'is_usb_connected()'
DEBUG:    1.2  adding overlay 'is_usb_connected_windows()'
DEBUG:    1.2  adding overlay 'post_yank_cleanup()'
DEBUG:    1.2  adding overlay 'prepare_addable_books()'
DEBUG:    1.2  adding overlay 'remove_books_from_metadata()'
DEBUG:    1.2  adding overlay 'set_busy_flag()'
DEBUG:    1.2  adding overlay 'set_cc_mapping()'
DEBUG:    1.2  adding overlay 'shutdown()'
DEBUG:    1.2  adding overlay 'sort_key()'
DEBUG:    1.2  adding overlay 'startup()'
DEBUG:    1.2  adding overlay 'sync_booklists()'
DEBUG:    1.2  adding overlay 'thumbnail()'
DEBUG:    1.2  adding overlay 'to_json()'
DEBUG:    1.2  adding overlay 'upload_books()'
DEBUG:    1.2  adding overlay 'xml_to_unicode()'
DEBUG:    1.2 iOSReaderApp:_initialize_overlay(Marvin) 
DEBUG:    1.2  existing thumb cache at 'C:\Users\Edward\AppData\Local\calibre-cache\Marvin\thumbs.zip'
DEBUG:    1.2  ~~~~~~~~~~~~~~~~~~~~~~~~~ switching to Marvin overlay ~~~~~~~~~~~~~~~~~~~~~~~~~~
Successfully initialized third party plugins: FanFictionDownLoader && Marvin XD && Quality Check && iOS reader applications
Starting up...
DEBUG:    3.1 iOSReaderApp:startup() 
DEBUG:    3.1 iOSReaderApp:_dump_installed_plugins() 
DEBUG:    3.1  plugin                author           version
DEBUG:    3.1  --------------------  ---------------  ------
DEBUG:    3.1  FanFictionDownLoader  Jim Miller       2.0.10 
DEBUG:    3.1  Marvin XD             Wulf C. Krueger  1.2.4  
DEBUG:    3.1  Quality Check         Grant Drake      1.9.11 
DEBUG:    3.1  --------------------  ---------------  ------
DEBUG:    3.1  Waiting for calibre connector...
Started up in 2.12 seconds with 4216 books
DEBUG:   38.5 iOSReaderApp:shutdown() 
DEBUG:   38.5 iOSReaderApp:eject()

**Comment by Philantrop** [comment]
Fixed since Version 1.4.6 - 1 January 2015
