### ISSUE TITLE
Ipad Version 7.1.2 with Goodreader Not Detected/iOS reader plugin installed and set to Goodreader

### ISSUE THREAD

**Issue by breezin** [Philantrop/calibre-ios-reader-applications#162]
calibre 1.48  isfrozen: True is64bit: False
Windows-XP-5.1.2600-SP3 Windows ('32bit', 'WindowsPE')
('Windows', 'XP', '5.1.2600')
Python 2.7.5
Windows: ('XP', '5.1.2600', 'SP3', 'Multiprocessor Free')
USB devices on system:
[u'usb\\root_hub&vid8086&pid2938&rev0002',
 u'usb\\root_hub&vid8086&pid2934&rev0002',
 u'usb\\root_hub&vid8086&pid2937&rev0002',
 u'usb\\root_hub&vid8086&pid2936&rev0002',
 u'usb\\root_hub&vid8086&pid2935&rev0002',
 u'usb\\root_hub&vid8086&pid2939&rev0002',
 u'usb\\root_hub20&vid8086&pid293a&rev0002',
 u'usb\\root_hub20&vid8086&pid293c&rev0002',
 u'usb\\vid_0461&pid_4d20&rev_0200',
 u'usb\\vid_046d&pid_082d&rev_0011',
 u'usb\\vid_046d&pid_082d&rev_0011&mi_00',
 u'usb\\vid_046d&pid_082d&rev_0011&mi_02',
 u'usb\\vid_04c5&pid_1078&rev_0100',
 u'usb\\vid_050d&pid_0237&rev_0007',
 u'usb\\vid_050d&pid_0237&rev_0007',
 u'usb\\vid_05ac&pid_12a9&rev_0240',
 u'usb\\vid_05ac&pid_12a9&rev_0240&mi_00',
 u'usb\\vid_0764&pid_0501&rev_0001',
 u'usb\\vid_0922&pid_0022&rev_0112',
 u'usb\\vid_0d8f&pid_1008&rev_0005',
 u'usb\\vid_18d1&pid_4e22&rev_0231',
 u'usb\\vid_18d1&pid_4e22&rev_0231&mi_00',
 u'usb\\vid_18d1&pid_4e22&rev_0231&mi_01']
Unable to get free space for drive: J
(21, 'GetDiskFreeSpaceEx', 'The device is not ready.')
Unable to get free space for drive: M
(21, 'GetDiskFreeSpaceEx', 'The device is not ready.')
Drives detected:

No disabled plugins
Looking for devices of type: MTP_DEVICE
Cannot detect MTP devices
MTP devices are not supported on Windows XP
 
Looking for devices...
	u'usb\\vid_18d1&pid_4e22&rev_0231'
	u'usb\\vid_18d1&pid_4e22&rev_0231&mi_00'
	u'usb\\vid_18d1&pid_4e22&rev_0231&mi_01'
	u'usb\\vid_05ac&pid_12a9&rev_0240'
 
Devices possibly connected: None

**Comment by Philantrop** [comment]
If you're still seeing this issue, please re-open this report.
