### ISSUE TITLE
Calibre Doesn't recognize iPhone 6, 8.3 iOS, GSM

### ISSUE THREAD

**Issue by Stroichik** [Philantrop/calibre-ios-reader-applications#185]
calibre 2.26  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: iOS reader applications && Marvin XD
USB devices on system:
[u'usb\root_hub20&vid8086&pid1e26&rev0004',
 u'usb\root_hub20&vid8086&pid1e2d&rev0004',
 u'usb\vid_046d&pid_0a1f&rev_0100',
 u'usb\vid_046d&pid_0a1f&rev_0100&mi_00',
 u'usb\vid_046d&pid_0a1f&rev_0100&mi_03',
 u'usb\vid_046d&pid_c228&rev_0110',
 u'usb\vid_046d&pid_c228&rev_0110&mi_00',
 u'usb\vid_046d&pid_c228&rev_0110&mi_01',
 u'usb\vid_046d&pid_c229&rev_1024',
 u'usb\vid_046d&pid_c229&rev_1024&mi_00',
 u'usb\vid_046d&pid_c229&rev_1024&mi_01',
 u'usb\vid_046d&pid_c24a&rev_7702',
 u'usb\vid_046d&pid_c24a&rev_7702&mi_00',
 u'usb\vid_046d&pid_c24a&rev_7702&mi_01',
 u'usb\vid_05ac&pid_12a8&rev_0702',
 u'usb\vid_05ac&pid_12a8&rev_0702&mi_00',
 u'usb\vid_05e3&pid_0607&rev_0801',
 u'usb\vid_0738&pid_1302&rev_0133',
 u'usb\vid_0846&pid_9011&rev_0001',
 u'usb\vid_8087&pid_0024&rev_0000',
 u'usb\vid_8087&pid_0024&rev_0000']
Traceback (most recent call last):
  File "site-packages\calibre\devices\scanner.py", line 85, in **call**
DriveError: No removable drives found
Drives detected:

No disabled plugins
Looking for devices of type: MTP_DEVICE
List of WPD PNP ids:
[u'\\?\usb#vid_05ac&pid_12a8&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}']
MTP device: \?\usb#vid_05ac&pid_12a8&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
{'device_version': u'8.3',
 'friendly_name': u'Apple iPhone',
 'has_bulk_properties': True,
 'has_storage': True,
 'manufacturer_name': u'Apple Inc.',
 'model_name': u'Apple iPhone',
 'protocol': u'MTP: 1.00',
 'serial_number': u'C39ND1FYG5MW',
 'storage': [{'capacity': 126825312256L,
              'capacity_objects': 0L,
              'description': u'Internal Storage',
              'filesystem': u'DCF',
              'free_objects': 21090L,
              'free_space': 31636385792L,
              'id': u's10001',
              'name': u'Internal Storage',
              'rw': True,
              'type': u'fixed_ram'}],
 'type': 'unknown'}
Not a suitable MTP device, ignoring

No suitable MTP devices found

Looking for devices of type: SMART_DEVICE_APP
All IP addresses {'{4A31F625-C92D-4EF2-B314-7DED6283A811}': [{'broadcast': '192.168.1.255', 'netmask': '255.255.255.0', 'addr': '192.168.1.137'}], '{D7E48E83-60CD-4419-A590-EC04387B6682}': [{'addr': '169.254.78.70'}], '{846EE342-7039-11DE-9D20-806E6F6E6963}': [{'broadcast': '127.255.255.255', 'netmask': '255.0.0.0', 'addr': '127.0.0.1'}], '{8C1A3B1C-705F-4821-9EE1-D44504FD7903}': [{'addr': '169.254.109.187'}]}
No device is connected

Looking for devices...
    u'usb\vid_05ac&pid_12a8&rev_0702'

Devices possibly connected: None

**Comment by KatyaL** [comment]
There's a known compatibility problem with iOS 8.3. Nothing can be done about it at this time. http://www.mobileread.com/forums/showthread.php?t=241143&page=32
