### ISSUE TITLE
Calibre not recognizing iPad

### ISSUE THREAD

**Issue by StevePeach** [Philantrop/calibre-ios-reader-applications#192]
Hi,
Recently change from iPad 2 to iPad Air 2 (Wifi). Calibre doesn't recognize the device. Tried to use old iPad 2 but now this doesn't trigger the Calibre device icon either.

calibre 2.28  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: Resize Cover && iOS reader applications
USB devices on system:
[u'usb\\root_hub&vid8086&pid2936&rev0002',
 u'usb\\root_hub&vid8086&pid2937&rev0002',
 u'usb\\root_hub&vid8086&pid2939&rev0002',
 u'usb\\root_hub&vid8086&pid2938&rev0002',
 u'usb\\root_hub&vid8086&pid2935&rev0002',
 u'usb\\root_hub&vid8086&pid2934&rev0002',
 u'usb\\root_hub20&vid8086&pid293c&rev0002',
 u'usb\\root_hub20&vid8086&pid293a&rev0002',
 u'usb\\vid_03f0&pid_2c17&rev_0100',
 u'usb\\vid_046d&pid_c52b&rev_1203',
 u'usb\\vid_046d&pid_c52b&rev_1203&mi_00',
 u'usb\\vid_046d&pid_c52b&rev_1203&mi_01',
 u'usb\\vid_046d&pid_c52b&rev_1203&mi_02',
 u'usb\\vid_04cc&pid_1521&rev_0200',
 u'usb\\vid_050d&pid_110a&rev_0000',
 u'usb\\vid_058f&pid_6362&rev_0126',
 u'usb\\vid_05ac&pid_12ab&rev_0503',
 u'usb\\vid_05ac&pid_12ab&rev_0503&mi_00',
 u'usb\\vid_05e3&pid_0608&rev_0702']
Unable to get free space for drive: F
(3, 'GetDiskFreeSpaceEx', 'The system cannot find the path specified.')
Unable to get free space for drive: G
(3, 'GetDiskFreeSpaceEx', 'The system cannot find the path specified.')
Unable to get free space for drive: H
(3, 'GetDiskFreeSpaceEx', 'The system cannot find the path specified.')
Unable to get free space for drive: I
(3, 'GetDiskFreeSpaceEx', 'The system cannot find the path specified.')
Drives detected:

No disabled plugins
Looking for devices of type: MTP_DEVICE
List of WPD PNP ids:
[u'\\\\?\\wpdbusenumroot#umb#2&37c186b&0&storage#volume#_??_usbstor#disk&ven_generic&prod_usb_ms_reader&rev_1.03#058f312d81b&30##{6ac27878-a6fa-4155-ba85-f98f491d4f33}',
 u'\\\\?\\wpdbusenumroot#umb#2&37c186b&0&storage#volume#_??_usbstor#disk&ven_generic&prod_usb_cf_reader&rev_1.01#058f312d81b&10##{6ac27878-a6fa-4155-ba85-f98f491d4f33}',
 u'\\\\?\\wpdbusenumroot#umb#2&37c186b&0&storage#volume#_??_usbstor#disk&ven_generic&prod_usb_sd_reader&rev_1.00#058f312d81b&00##{6ac27878-a6fa-4155-ba85-f98f491d4f33}',
 u'\\\\?\\wpdbusenumroot#umb#2&37c186b&0&storage#volume#_??_usbstor#disk&ven_generic&prod_usb_sm_reader&rev_1.02#058f312d81b&20##{6ac27878-a6fa-4155-ba85-f98f491d4f33}',
 u'\\\\?\\usb#vid_05ac&pid_12ab&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}']
MTP device: \\?\usb#vid_05ac&pid_12ab&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
{'device_version': u'8.3',
 'friendly_name': u'Apple iPad',
 'has_bulk_properties': True,
 'has_storage': True,
 'manufacturer_name': u'Apple Inc.',
 'model_name': u'Apple iPad',
 'protocol': u'MTP: 1.00',
 'serial_number': u'DLXP3LC3G5W0',
 'storage': [{'capacity': 63417876480L,
              'capacity_objects': 0L,
              'description': u'Internal Storage',
              'filesystem': u'DCF',
              'free_objects': 34690L,
              'free_space': 52035809280L,
              'id': u's10001',
              'name': u'Internal Storage',
              'rw': True,
              'type': u'fixed_ram'}],
 'type': 'unknown'}
Not a suitable MTP device, ignoring

No suitable MTP devices found
 
Looking for devices of type: SMART_DEVICE_APP
All IP addresses {'{685F50ED-0375-4A99-9474-8487A2ECE1E2}': [{'addr': '192.168.1.67', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}], '{6667FE8A-FB5A-11E2-AF0B-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
No device is connected
 
Looking for devices...
	u'usb\\vid_05ac&pid_12ab&rev_0503'
 
Devices possibly connected: None

**Comment by KatyaL** [comment]
If you're using iOS 8.3, there's a known compatibility problem with it. Nothing can be done about it at this time. http://www.mobileread.com/forums/showthread.php?t=241143&page=33

**Comment by StevePeach** [comment]
Katyal,
Thanks for response.
