### ISSUE TITLE
iphone 4s 32Gb vodafone UK - device not recognised by calibre

### ISSUE THREAD

**Issue by menelion** [Philantrop/calibre-ios-reader-applications#98]
calibre 1.48  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.5
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
USB devices on system:
[u'usb\\root_hub20&vid1002&pid4396&rev0000',
 u'usb\\vid_0d8c&pid_013c&rev_0100&mi_03',
 u'usb\\vid_04d9&pid_a067&rev_0102&mi_02',
 u'usb\\vid_045e&pid_00dd&rev_0173',
 u'usb\\vid_04d9&pid_a067&rev_0102&mi_01',
 u'usb\\vid_1a40&pid_0201&rev_0100',
 u'usb\\vid_04d9&pid_a067&rev_0102&mi_00',
 u'usb\\vid_05ac&pid_1297&rev_0310&mi_00',
 u'usb\\root_hub20&vid1002&pid4396&rev0000',
 u'usb\\vid_0d8c&pid_013c&rev_0100',
 u'usb\\vid_05ac&pid_1297&rev_0310',
 u'usb\\via_root_hub&vid1106&pid3483&rev0001',
 u'usb\\root_hub&vid1002&pid4399&rev0000',
 u'usb\\root_hub&vid1002&pid4398&rev0000',
 u'usb\\root_hub&vid1002&pid4397&rev0000',
 u'usb\\vid_0d8c&pid_013c&rev_0100&mi_00',
 u'usb\\vid_0bda&pid_8172&rev_0200',
 u'usb\\vid_058f&pid_6366&rev_0100',
 u'usb\\root_hub&vid1002&pid4398&rev0000',
 u'usb\\vid_04d9&pid_a067&rev_0102',
 u'usb\\root_hub&vid1002&pid4397&rev0000',
 u'usb\\vid_045e&pid_00dd&rev_0173&mi_01',
 u'usb\\vid_045e&pid_00dd&rev_0173&mi_00']
Unable to get free space for drive: D
(21, 'GetDiskFreeSpaceEx', 'The device is not ready.')
Drives detected:

No disabled plugins
Looking for devices of type: MTP_DEVICE
List of WPD PNP ids:
[u'\\\\?\\usb#vid_05ac&pid_1297&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}',
 u'\\\\?\\swd#wpdbusenum#_??_usbstor#disk&ven_multiple&prod_card__reader&rev_1.00#058f63666433&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}#{6ac27878-a6fa-4155-ba85-f98f491d4f33}']
MTP device: \\?\usb#vid_05ac&pid_1297&mi_00#0#{6ac27878-a6fa-4155-ba85-f98f491d4f33}
{'device_version': u'7.1.2',
 'friendly_name': u'Apple iPhone',
 'has_bulk_properties': True,
 'has_storage': True,
 'manufacturer_name': u'Apple Inc.',
 'model_name': u'Apple iPhone',
 'protocol': u'MTP: 1.00',
 'serial_number': u'87044YHZA4T',
 'storage': [{'capacity': 31977373696L,
              'capacity_objects': 0L,
              'description': u'Internal Storage',
              'filesystem': u'DCF',
              'free_objects': 17840L,
              'free_space': 26761371648L,
              'id': u's10001',
              'name': u'Internal Storage',
              'rw': True,
              'type': u'fixed_ram'}],
 'type': 'unknown'}
Not a suitable MTP device, ignoring

No suitable MTP devices found
 
Looking for devices...
 
Devices possibly connected: None

**Comment by Philantrop** [comment]
Support for this model has been added quite some time ago.
