### ISSUE TITLE
Marvin XD hangs when connecting to iPhone or iPad Marvin

### ISSUE THREAD

**Issue by evanbernstein** [Philantrop/calibre-ios-reader-applications#99]
I used to use Marvin XD and Marvin on my iPhone and iPad all the time.  Sometime in the last few weeks it stopped working (I synced something last on July 20th).

When I start calibre connect in Marvin will say that they are connected, but the job icon in the lower right never stops spinning.  The jobs 'Get list of books on device' and 'Get device information' say 100% but the 'Get list of books on device' keeps increasing its timer and they never finish.

When I then click on Marvin XD it shows the popup of loading all the information.  Tells me that there are some books that don't match popup window.  When I dismiss that, calibre is now hung and I have to 'Force Quit' it.

- OS X: 10.9.4
- calibre: 1.48
  - English
- iOS reader application: 1.4.1
- Marvin XD: 1.2.2
- iTunes: 11.3.1 (2)

- iPad 4th gen 32G
- iPhone 5 64G

Let me know if there is anything I can do to help.

below is the debug log:

calibre 1.48  isfrozen: True is64bit: True
Darwin-13.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '13.3.0', 'Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64')
Python 2.7.5
OSX: ('10.9.4', ('', '', ''), 'x86_64')
DEBUG:    0.0 iOSReaderApp:initialize(v1.4.1) 
DEBUG:    0.0 iOSReaderApp:compile_ui() 
DEBUG:    0.0 iOSReaderApp:_init_prefs(prefs created under v1.4.0) 
DEBUG:    0.0  debug_libimobiledevice: True
DEBUG:    0.0  debug_plugin: True
DEBUG:    0.0  development_mode: False
DEBUG:    0.0  device_booklist_cache_limit: 10
DEBUG:    0.0  device_booklist_caching: False
DEBUG:    0.0  kindle_enabled_formats: [u'MOBI']
DEBUG:    0.0  kindle_supported_formats: [u'MOBI', u'PDF']
DEBUG:    0.0  marvin_edit_collections_cb: False
DEBUG:    0.0  marvin_enabled_collection_fields: []
DEBUG:    0.0  marvin_protect_rb: False
DEBUG:    0.0  marvin_replace_rb: True
DEBUG:    0.0  marvin_update_rb: False
DEBUG:    0.0  plugin_diagnostics: True
DEBUG:    0.0  preferred_reader_app: u'Marvin'
DEBUG:    0.0 libiMobileDevice:__init__() 
DEBUG:    0.0 libiMobileDevice:load_library(OS X) 
DEBUG:    0.0   libimobiledevice loaded from '/Applications/calibre.app/Contents/Frameworks/libimobiledevice.4.dylib'
DEBUG:    0.0   libplist loaded from '/Applications/calibre.app/Contents/Frameworks/libplist.1.dylib'
DEBUG:    0.0 iOSReaderApp:_get_connected_device_info() 
DEBUG:    0.0 libiMobileDevice:get_device_list() 
DEBUG:    0.0 libiMobileDevice:_idevice_get_device_list() 
DEBUG:    1.0   ['5c5222cb765009d2c6251b54f434e5d692c672c2']
DEBUG:    1.0 libiMobileDevice:connect_idevice() 
DEBUG:    1.0 libiMobileDevice:_idevice_new() 
DEBUG:    2.0         conn_type: CONNECTION_USBMUXD
DEBUG:    2.0              udid: 5c5222cb765009d2c6251b54f434e5d692c672c2
DEBUG:    2.0 libiMobileDevice:_lockdown_client_new_with_handshake() 
DEBUG:    2.1 libiMobileDevice:_lockdown_get_device_name() 
DEBUG:    2.1       device_name: evan's iPad
DEBUG:    2.1 libiMobileDevice:_lockdown_start_service(com.apple.mobile.installation_proxy) 
DEBUG:    2.1 libiMobileDevice:get_preferences() 
DEBUG:    2.1 libiMobileDevice:_lockdown_get_value() 
DEBUG:    2.1 libiMobileDevice:disconnect_idevice(evan's iPad) 
DEBUG:    2.1   device already disconnected
DEBUG:    2.1 libiMobileDevice:mount_ios_media_folder() 
DEBUG:    2.1 libiMobileDevice:_idevice_new() 
DEBUG:    3.1         conn_type: CONNECTION_USBMUXD
DEBUG:    3.1              udid: 5c5222cb765009d2c6251b54f434e5d692c672c2
DEBUG:    3.1 libiMobileDevice:_lockdown_client_new_with_handshake() 
DEBUG:    3.1 libiMobileDevice:_lockdown_start_service(com.apple.afc) 
DEBUG:    3.1 libiMobileDevice:_afc_client_new() 
DEBUG:    3.1 libiMobileDevice:_lockdown_client_free() 
DEBUG:    3.1 libiMobileDevice:_afc_get_device_info() 
DEBUG:    3.1             Model: iPad3,4
DEBUG:    3.1       FSFreeBytes: 4078137344
DEBUG:    3.1       FSBlockSize: 4096
DEBUG:    3.1      FSTotalBytes: 29874524160
DEBUG:    3.1 libiMobileDevice:_afc_client_free() 
DEBUG:    3.1 libiMobileDevice:_idevice_free() 
DEBUG:    3.1  mounting 'com.appstafarian.MarvinIP'
DEBUG:    3.1 libiMobileDevice:mount_ios_app(com.appstafarian.MarvinIP) 
DEBUG:    3.1 libiMobileDevice:_idevice_new() 
DEBUG:    4.1         conn_type: CONNECTION_USBMUXD
DEBUG:    4.1              udid: 5c5222cb765009d2c6251b54f434e5d692c672c2
DEBUG:    4.1 libiMobileDevice:_lockdown_client_new_with_handshake() 
DEBUG:    4.2 libiMobileDevice:_lockdown_get_device_name() 
DEBUG:    4.2       device_name: evan's iPad
DEBUG:    4.2 libiMobileDevice:_lockdown_start_service(com.apple.mobile.house_arrest) 
DEBUG:    4.2 libiMobileDevice:_house_arrest_client_new() 
DEBUG:    4.2 libiMobileDevice:_house_arrest_send_command(command=u'VendContainer' appid='com.appstafarian.MarvinIP') 
DEBUG:    4.2 libiMobileDevice:_house_arrest_get_result() 
DEBUG:    4.2            STATUS: Complete
DEBUG:    4.2 libiMobileDevice:_afc_client_new_from_house_arrest_client() 
DEBUG:    4.2 libiMobileDevice:_lockdown_client_free() 
DEBUG:    4.2 libiMobileDevice:mount_ios_app('com.appstafarian.MarvinIP' mounted) 
DEBUG:    4.2 libiMobileDevice:disconnect_idevice(evan's iPad) 
DEBUG:    4.2 libiMobileDevice:_afc_client_free() 
DEBUG:    4.2 libiMobileDevice:_house_arrest_client_free() 
DEBUG:    4.2 libiMobileDevice:_idevice_free() 
DEBUG:    4.2 iOSReaderApp:_class_reconfigure('Marvin') 
DEBUG:    4.2 iOSReaderApp:_load_reader_app_overlays('Marvin') 
DEBUG:    4.2  loading 58 overlays
DEBUG:    4.2  adding overlay '_compare_mainDb_profiles()'
DEBUG:    4.2  adding overlay '_cover_subpath()'
DEBUG:    4.2  adding overlay '_cover_to_thumb()'
DEBUG:    4.2  adding overlay '_create_cover_element()'
DEBUG:    4.2  adding overlay '_create_empty_booklist_db()'
DEBUG:    4.2  adding overlay '_create_new_book()'
DEBUG:    4.2  adding overlay '_dehydrate_booklist()'
DEBUG:    4.2  adding overlay '_establish_local_booklist_db_path()'
DEBUG:    4.2  adding overlay '_evaluate_original_cover()'
DEBUG:    4.2  adding overlay '_evaluate_replaceable_cover()'
DEBUG:    4.2  adding overlay '_get_field_items()'
DEBUG:    4.2  adding overlay '_get_opf_tree()'
DEBUG:    4.2  adding overlay '_get_opf_xml()'
DEBUG:    4.2  adding overlay '_initialize_overlay()'
DEBUG:    4.2  adding overlay '_localize_booklist_db()'
DEBUG:    4.2  adding overlay '_localize_database_path()'
DEBUG:    4.2  adding overlay '_parse_version()'
DEBUG:    4.2  adding overlay '_parse_xml()'
DEBUG:    4.2  adding overlay '_profile_db()'
DEBUG:    4.2  adding overlay '_rehydrate_booklist()'
DEBUG:    4.2  adding overlay '_remove_existing_copy()'
DEBUG:    4.2  adding overlay '_report_upload_results()'
DEBUG:    4.2  adding overlay '_reset_ios_connection()'
DEBUG:    4.2  adding overlay '_restore_from_snapshot()'
DEBUG:    4.2  adding overlay '_schedule_metadata_update()'
DEBUG:    4.2  adding overlay '_snapshot_booklist()'
DEBUG:    4.2  adding overlay '_stage_command_file()'
DEBUG:    4.2  adding overlay '_update_epub_metadata()'
DEBUG:    4.2  adding overlay '_validate_dehydrated_booklist()'
DEBUG:    4.2  adding overlay '_wait_for_command_completion()'
DEBUG:    4.2  adding overlay '_watchdog_timed_out()'
DEBUG:    4.2  adding overlay '_xform_metadata_via_plugboard()'
DEBUG:    4.2  adding overlay 'add_books_to_metadata()'
DEBUG:    4.2  adding overlay 'books()'
DEBUG:    4.2  adding overlay 'can_handle()'
DEBUG:    4.2  adding overlay 'can_handle_windows()'
DEBUG:    4.2  adding overlay 'delete_books()'
DEBUG:    4.2  adding overlay 'eject()'
DEBUG:    4.2  adding overlay 'from_json()'
DEBUG:    4.2  adding overlay 'get_busy_flag()'
DEBUG:    4.2  adding overlay 'get_cc_mapping()'
DEBUG:    4.2  adding overlay 'get_file()'
DEBUG:    4.2  adding overlay 'guess_type()'
DEBUG:    4.2  adding overlay 'is_usb_connected()'
DEBUG:    4.2  adding overlay 'is_usb_connected_windows()'
DEBUG:    4.2  adding overlay 'post_yank_cleanup()'
DEBUG:    4.2  adding overlay 'prepare_addable_books()'
DEBUG:    4.2  adding overlay 'remove_books_from_metadata()'
DEBUG:    4.2  adding overlay 'set_busy_flag()'
DEBUG:    4.2  adding overlay 'set_cc_mapping()'
DEBUG:    4.2  adding overlay 'shutdown()'
DEBUG:    4.2  adding overlay 'sort_key()'
DEBUG:    4.2  adding overlay 'startup()'
DEBUG:    4.2  adding overlay 'sync_booklists()'
DEBUG:    4.2  adding overlay 'thumbnail()'
DEBUG:    4.2  adding overlay 'to_json()'
DEBUG:    4.2  adding overlay 'upload_books()'
DEBUG:    4.2  adding overlay 'xml_to_unicode()'
DEBUG:    4.2 iOSReaderApp:_initialize_overlay(Marvin) 
DEBUG:    4.2  existing thumb cache at '/Users/evan/Library/Caches/calibre/Marvin/thumbs.zip'
DEBUG:    4.2  ~~~~~~~~~~~~~~~~~~~~~~~~~ switching to Marvin overlay ~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting up...
DEBUG:    5.6 iOSReaderApp:startup() 
DEBUG:    5.6 iOSReaderApp:_dump_installed_plugins() 
DEBUG:    5.6  plugin                                    author                                                        version
DEBUG:    5.6  ----------------------------------------  ------------------------------------------------------------  ------
DEBUG:    5.6  DeDRM                                     DiapDealer, Apprentice Alf, The Dark Reverser and i♥cabbages  6.0.8  
DEBUG:    5.6  eReader PDB 2 PML                         DiapDealer                                                    0.0.6  
DEBUG:    5.6  Ignoble Epub DeDRM                        DiapDealer                                                    0.1.6  
DEBUG:    5.6  Inept Epub DeDRM                          DiapDealer                                                    0.1.7  
DEBUG:    5.6  Inept PDF DeDRM                           DiapDealer                                                    0.1.5  
DEBUG:    5.6  K4PC, K4Mac, Kindle Mobi and Topaz DeDRM  DiapDealer, SomeUpdates                                       0.3.8  
DEBUG:    5.6  Kindle and Mobipocket DeDRM               DiapDealer, SomeUpdates, mdlnx, Apprentice Alf                0.4.5  
DEBUG:    5.6  Marvin XD                                 Wulf C. Krueger                                               1.2.2  
DEBUG:    5.6  Modify ePub                               Grant Drake                                                   1.3.10 
DEBUG:    5.6  Quality Check                             Grant Drake                                                   1.9.11 
DEBUG:    5.6  ----------------------------------------  ------------------------------------------------------------  ------
DEBUG:    5.6  Waiting for calibre connector...
DEBUG:    5.6 libiMobileDevice:get_device_list() 
DEBUG:    5.6 libiMobileDevice:_idevice_get_device_list() 
Started up in 1.79 seconds with 397 books
DEBUG:    6.6   ['5c5222cb765009d2c6251b54f434e5d692c672c2']
DEBUG:    6.6 libiMobileDevice:mount_ios_app(com.appstafarian.MarvinIP) 
DEBUG:    6.6 libiMobileDevice:_idevice_new() 
DEBUG:    7.6         conn_type: CONNECTION_USBMUXD
DEBUG:    7.6              udid: 5c5222cb765009d2c6251b54f434e5d692c672c2
DEBUG:    7.6 libiMobileDevice:_lockdown_client_new_with_handshake() 
DEBUG:    7.7 libiMobileDevice:_lockdown_get_device_name() 
DEBUG:    7.7       device_name: evan's iPad
DEBUG:    7.7 libiMobileDevice:_lockdown_start_service(com.apple.mobile.house_arrest) 
DEBUG:    7.7 libiMobileDevice:_house_arrest_client_new() 
DEBUG:    7.7 libiMobileDevice:_house_arrest_send_command(command=u'VendContainer' appid='com.appstafarian.MarvinIP') 
DEBUG:    7.7 libiMobileDevice:_house_arrest_get_result() 
DEBUG:    7.7            STATUS: Complete
DEBUG:    7.7 libiMobileDevice:_afc_client_new_from_house_arrest_client() 
DEBUG:    7.7 libiMobileDevice:_lockdown_client_free() 
DEBUG:    7.7 libiMobileDevice:mount_ios_app('com.appstafarian.MarvinIP' mounted) 
DEBUG:    7.7 libiMobileDevice:exists(u'/Library/calibre/connected.xml') 
DEBUG:    7.7 libiMobileDevice:_afc_get_file_info(u'/Library/calibre/connected.xml') 
DEBUG:    7.7 libiMobileDevice:_afc_get_file_info( ERROR: Object not found (8) path:u'/Library/calibre/connected.xml') 
DEBUG:    9.7 libiMobileDevice:get_device_list() 
DEBUG:    9.7 libiMobileDevice:_idevice_get_device_list() 
DEBUG:   10.7   ['5c5222cb765009d2c6251b54f434e5d692c672c2']
DEBUG:   10.7 libiMobileDevice:exists(u'/Library/calibre/connected.xml') 
DEBUG:   10.7 libiMobileDevice:_afc_get_file_info(u'/Library/calibre/connected.xml') 
DEBUG:   10.7 libiMobileDevice:_afc_get_file_info( ERROR: Object not found (8) path:u'/Library/calibre/connected.xml') 
DEBUG:   12.7 libiMobileDevice:get_device_list() 
DEBUG:   12.7 libiMobileDevice:_idevice_get_device_list() 
DEBUG:   13.7   ['5c5222cb765009d2c6251b54f434e5d692c672c2']
DEBUG:   13.7 libiMobileDevice:exists(u'/Library/calibre/connected.xml') 
DEBUG:   13.7 libiMobileDevice:_afc_get_file_info(u'/Library/calibre/connected.xml') 
DEBUG:   13.7 lib* Notification delivered.
iMobileDevice:_afc_get_file_info( ERROR: Object not found (8) path:u'/Library/calibre/connected.xml') 
DEBUG:   15.7 libiMobileDevice:get_device_list() 
DEBUG:   15.7 libiMobileDevice:_idevice_get_device_list() 
DEBUG:   16.7   ['5c5222cb765009d2c6251b54f434e5d692c672c2']
DEBUG:   16.7 libiMobileDevice:exists(u'/Library/calibre/connected.xml') 
DEBUG:   16.7 libiMobileDevice:_afc_get_file_info(u'/Library/calibre/connected.xml') 
DEBUG:   16.7 libiMobileDevice:_afc_get_file_info( ERROR: Object not found (8) path:u'/Library/calibre/connected.xml') 
DEBUG:   18.7 libiMobileDevice:get_device_list() 
DEBUG:   18.7 libiMobileDevice:_idevice_get_device_list() 
DEBUG:   19.7   ['5c5222cb765009d2c6251b54f434e5d692c672c2']
DEBUG:   19.7 libiMobileDevice:exists(u'/Library/calibre/connected.xml') 
DEBUG:   19.7 libiMobileDevice:_afc_get_file_info(u'/Library/calibre/connected.xml') 
DEBUG:   19.7 libiMobileDevice:read(u'/Library/calibre/connected.xml' mode='r') 
DEBUG:   19.7 libiMobileDevice:_afc_file_open(u'/Library/calibre/connected.xml' mode='r') 
DEBUG:   19.7 libiMobileDevice:_afc_get_file_info(u'/Library/calibre/connected.xml') 
DEBUG:   19.7 libiMobileDevice:_afc_file_read(handle:1 size:208 mode='r') 
DEBUG:   19.7 libiMobileDevice:_afc_file_close(handle:1) 
DEBUG:   19.7  Marvin version: (2, 7, 2)
DEBUG:   19.7 iOSReaderApp:reset() 
DEBUG:   19.7 iOSReaderApp:open() 
DEBUG:   19.7   Vendor ID (vid):05ac Product ID: (pid):12ab
DEBUG:   21.1 iOSReaderApp:set_progress_reporter() 
Job: 1 Get device information started
DEBUG:   21.1 iOSReaderApp:get_device_information() 
DEBUG:   21.1   DeviceClass          : iPad
DEBUG:   21.1   DeviceColor          : black
DEBUG:   21.1   DeviceName           : evan's iPad
DEBUG:   21.1   FSBlockSize          : 4096
DEBUG:   21.1   FSFreeBytes          : 4,078,137,344
DEBUG:   21.1   FSTotalBytes         : 29,874,524,160
DEBUG:   21.1   FirmwareVersion      : iBoot-1940.10.58
DEBUG:   21.1   HardwareModel        : P101AP
DEBUG:   21.1   ModelNumber          : MD511
DEBUG:   21.1   PasswordProtected    : False
DEBUG:   21.1   ProductType          : iPad3,4
DEBUG:   21.1   ProductVersion       : 7.1.2
DEBUG:   21.1   SerialNumber         : DMPJM1T5F183
DEBUG:   21.1   TimeIntervalSince1970: 1407691816.92
DEBUG:   21.1   TimeZone             : America/New_York
DEBUG:   21.1   TimeZoneOffsetFromUTC: -14400.0
DEBUG:   21.1   UniqueDeviceID       : 5c5222cb765009d2c6251b54f434e5d692c672c2
DEBUG:   21.1 iOSReaderApp:free_space() 
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
DEBUG:   21.1 iOSReaderApp:set_progress_reporter() 
Job: 2 Get list of books on device started
DEBUG:   21.1 iOSReaderApp:books() 
DEBUG:   21.1 iOSReaderApp:_localize_database_path() 
DEBUG:   21.1 libiMobileDevice:stat(u'/Library/mainDb.sqlite') 
DEBUG:   21.1 libiMobileDevice:_afc_get_file_info(u'/Library/mainDb.sqlite') 
DEBUG:   21.1  copying local_db from u'/Library/mainDb.sqlite'
DEBUG:   21.1 libiMobileDevice:copy_from_idevice() 
DEBUG:   21.1  src: u'/Library/mainDb.sqlite'
DEBUG:   21.1  dst: /var/folders/vd/lw6jbz951n7ckysnys2wyp700000gn/T/calibre_1.48.0_tmp_ZYgYvZ/IjE5KP_ios_local_db/mainDb.sqlite
DEBUG:   21.1 libiMobileDevice:_afc_file_open(u'/Library/mainDb.sqlite' mode='rb') 
DEBUG:   21.1 libiMobileDevice:_afc_get_file_info(u'/Library/mainDb.sqlite') 
DEBUG:   21.1  file_size: 7,015,424 bytes
DEBUG:   21.1  copying 7,015,424 bytes
DEBUG:   21.1 libiMobileDevice:_afc_file_read(handle:1 size:7,015,424 mode='rb') 
Job: 1 Get device information finished
No details available.
DEBUG:   21.5 libiMobileDevice:_afc_file_close(handle:1) 
DEBUG:   21.5 libiMobileDevice:_afc_get_file_info(u'/Library/mainDb.sqlite') 
DEBUG:   21.5 iOSReaderApp:_restore_from_snapshot() 
DEBUG:   21.5  Analyzing local booklist
DEBUG:   21.5 libiMobileDevice:stat(u'/Library/Application Support/com.appstafarian.marvin.covers') 
DEBUG:   21.5 libiMobileDevice:_afc_get_file_info(u'/Library/Application Support/com.appstafarian.marvin.covers') 
DEBUG:   21.5  local booklist.db validated
DEBUG:   21.9 iOSReaderApp:_rehydrate_booklist() 
DEBUG:   21.9 iOSReaderApp:_log_metrics(Marvin) 
DEBUG:   66.9 iOSReaderApp:shutdown() 
DEBUG:   66.9 iOSReaderApp:eject() 
DEBUG:   66.9 libiMobileDevice:disconnect_idevice(evan's iPad) 
DEBUG:   66.9 libiMobileDevice:_afc_client_free() 
DEBUG:   66.9 libiMobileDevice:_house_arrest_client_free() 
DEBUG:   66.9 libiMobileDevice:_idevice_free()

**Comment by Philantrop** [comment]
If you're still seeing this issue, please re-open this report.
